[server]
ip = "0.0.0.0"
port = 8080
dist_path = "./dist"
open_modules = ["CloudM.AuthClerk", "CloudM",  "CloudM.email_services"]
init_modules = ["CloudM"]
watch_modules = ["CloudM", "TruthSeeker", "DoNext"]


[toolbox]
client_prifix="collective-debugApi-"
timeout_seconds = 60
max_instances = 2

[session]
secret_key = "F95AF20084A99457B6C0FDD43AD3E4607654A7EA26E3CA90F578CF52408D076D"
duration_minutes = 3600


[env]
PYO3_PYTHON={value = "python3" , relative = false, force = true }
